# html lang
language: en

title: MKPT
subtitle: 'subtitle goes here'

# main menu navigation
menu:
  All: /
  Blog: /tags/blog
  Code: /tags/code
  Friends: /friends
  About: /about
  Archives: /archives

# stylesheets loaded in the <head>
stylesheets:
  - /css/oasis.css

# scripts loaded in the end of the body
scripts:
  - /js/oasis.js

logo:
  - ./asset/logo.JPG
