# html lang
language: en

title: mkpt
subtitle: 'subtitle goes here'

# main menu navigation
menu:
  all: /
  blog: /tags/blog
  code: /tags/code
  #Friends: /friends
  bio: /about
  archives: /archives

# stylesheets loaded in the <head>
stylesheets:
  - /css/oasis.css

# scripts loaded in the end of the body
scripts:
  - /js/oasis.js

logo:
  - ./assets/logo.JPG

favicon:
  small: /favicon.ico
  medium: /favicon-32x32.png